# Generated by Django 2.2.3 on 2019-07-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='addCartNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='payNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='saveNum',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SaveNum',
        ),
    ]
