# Generated by Django 2.2.3 on 2019-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='desc',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
