# Generated by Django 2.2.3 on 2019-07-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0002_auto_20190717_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='Categorie.title', to='sadia.Categorie'),
        ),
    ]
