# Generated by Django 2.2.3 on 2019-07-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0002_auto_20190716_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
