# Generated by Django 2.2.3 on 2019-07-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0003_auto_20190717_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadia.Categorie'),
        ),
    ]
