# Generated by Django 2.2.3 on 2019-07-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0003_goods_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='nnn', max_length=20)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sadia.Goods')),
            ],
        ),
    ]
