# Generated by Django 2.2.3 on 2019-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadia', '0004_classify'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img1',
            field=models.ImageField(default=1, upload_to='goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='img2',
            field=models.ImageField(default=232, upload_to='goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='img3',
            field=models.ImageField(default=1231, upload_to='goods'),
            preserve_default=False,
        ),
    ]
