# Generated by Django 2.2.3 on 2019-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='ads')),
            ],
        ),
    ]
